# General Jekyll Config
highlighter: rogue
name: Octocat's Wanderings
description: foo bar
url: "http://shizuoz.github.io"

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

# Build config
